In [5]:
import os

import pandas as pd
from pymongo import MongoClient

In [6]:
mongo_uri = os.getenv('MONGODB_URI', 'mongodb://localhost:27017')
client = MongoClient(mongo_uri)
database = client['data_major']
collection = database['facebook_reviews']
mongo_uri

'mongodb://localhost:27017'

In [7]:
document_count = collection.count_documents({})
document_count

346202

In [8]:
sample_documents = list(collection.find({}, {'_id': 0}).limit(5))
sample_df = pd.DataFrame(sample_documents)
sample_df

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion,review_length,word_count,sentiment,review_year,review_month,load_source
0,6d8c5af9-e48a-4c63-9f68-98e1e658a357,Uddhav Bhasinge,Hello Dear Sir.. My Facebook Account is disabl...,4,0,559.1.0.52.72,2026-05-07 07:58:04+00:00,559.1.0.52.72,496,86,positivo,2026,5,facebook_reviews_clean.csv.gz
1,df39cb1c-44ce-49f4-972b-e7cc2c44ff7d,Sandy Cummings,The audio in a lot of the reels is awful! Plea...,4,1,559.1.0.52.72,2026-05-07 03:26:09+00:00,559.1.0.52.72,153,29,positivo,2026,5,facebook_reviews_clean.csv.gz
2,6fff7b38-a5b9-459c-a4b5-103fcb55866f,Kamran Siyal,very frustrating now a days Facebook suspended...,1,0,559.1.0.52.72,2026-05-07 03:12:07+00:00,559.1.0.52.72,106,16,negativo,2026,5,facebook_reviews_clean.csv.gz
3,0f59821f-f565-4014-a630-7df9a2beb691,James Bond,reels are now shared as a link instead of a vi...,1,0,558.0.0.70.72,2026-05-07 03:10:45+00:00,558.0.0.70.72,71,15,negativo,2026,5,facebook_reviews_clean.csv.gz
4,9bfda33d-2052-42b6-a857-015aac413b62,Francis Great,"“In this country where trust is hard to find, ...",5,0,556.1.0.63.64,2026-05-07 02:32:04+00:00,556.1.0.63.64,162,26,positivo,2026,5,facebook_reviews_clean.csv.gz

In [9]:
list(collection.index_information().keys())

['_id_', 'reviewId_1', 'at_-1', 'sentiment_1']

In [10]:
positive_reviews = list(collection.find({'sentiment': 'positivo'}, {'_id': 0}).limit(5))
pd.DataFrame(positive_reviews)

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion,review_length,word_count,sentiment,review_year,review_month,load_source
0,6d8c5af9-e48a-4c63-9f68-98e1e658a357,Uddhav Bhasinge,Hello Dear Sir.. My Facebook Account is disabl...,4,0,559.1.0.52.72,2026-05-07 07:58:04+00:00,559.1.0.52.72,496,86,positivo,2026,5,facebook_reviews_clean.csv.gz
1,df39cb1c-44ce-49f4-972b-e7cc2c44ff7d,Sandy Cummings,The audio in a lot of the reels is awful! Plea...,4,1,559.1.0.52.72,2026-05-07 03:26:09+00:00,559.1.0.52.72,153,29,positivo,2026,5,facebook_reviews_clean.csv.gz
2,9bfda33d-2052-42b6-a857-015aac413b62,Francis Great,"“In this country where trust is hard to find, ...",5,0,556.1.0.63.64,2026-05-07 02:32:04+00:00,556.1.0.63.64,162,26,positivo,2026,5,facebook_reviews_clean.csv.gz
3,28d4c82d-a63c-4c27-8eaa-9fdb2b08073e,Adeel Virk,"I used Facebook for selling local products, an...",4,1,559.1.0.52.72,2026-05-07 01:43:34+00:00,559.1.0.52.72,427,68,positivo,2026,5,facebook_reviews_clean.csv.gz
4,7dbf5dd0-a098-4f6f-b138-860ee80b974d,Willie Mcintyre,HE LAID THAT OUT PERFECTLY I REALLY APPRECIATE...,5,0,558.0.0.70.72,2026-05-07 00:18:27+00:00,558.0.0.70.72,65,11,positivo,2026,5,facebook_reviews_clean.csv.gz